# Generated by Django 4.0.4 on 2022-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargemix',
            name='fesimg_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
