# Generated by Django 4.0.4 on 2022-05-19 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0002_alter_chargemix_fesimg_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargemix',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chargemixproduct',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chargemixproductelement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='chargemixproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chargemixproduct',
            name='updated',
        ),
        migrations.AddField(
            model_name='chargemix',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargemix',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
