# Generated by Django 4.0.4 on 2022-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0003_alter_chargemix_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_curr_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_final_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_max_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_min_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_qty_roundoff',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chargemixproductelement',
            name='element',
            field=models.TextField(blank=True, default=''),
        ),
    ]
