# Generated by Django 4.0.4 on 2022-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0004_alter_chargemixproduct_product_curr_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemix',
            name='target_chemistry',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='name',
            field=models.TextField(),
        ),
    ]
