# Generated by Django 4.0.4 on 2022-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0005_chargemix_target_chemistry_alter_chargemix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('furnace mat', 'furnace_material'), ('inoculant', 'inoculant'), ('additive', 'additive'), ('nodularization mat', 'nodularization_material')], default='furnace_material', max_length=50),
        ),
    ]
