# Generated by Django 4.0.4 on 2022-05-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0007_chargemixproduct_product_element_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chargemix',
            index=models.Index(fields=['created'], name='newc_charge_created_69d0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['name'], name='newc_elemen_name_f6d4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['symbol'], name='newc_elemen_symbol_da96b0_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['name'], name='newc_grade_name_4cda20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type'], name='newc_produc_type_9558a5_idx'),
        ),
    ]
