# Generated by Django 4.0.4 on 2022-05-20 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0010_remove_element_newc_elemen_name_f6d4f9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargemixproduct',
            name='metal_recov_rate_lte_100',
        ),
        migrations.RemoveConstraint(
            model_name='chargemixproduct',
            name='product_qty_roundoff_lte_10',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='price_gte_1',
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='tapping_temp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='tapping_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='metal_recov_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='product_qty_roundoff',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('furnace_mat', 'furnace material'), ('ladle_mat', 'ladle material'), ('additive', 'additive'), ('nodularization_mat', 'nodularization material')], default='furnace_material', max_length=50),
        ),
    ]
