# Generated by Django 4.0.4 on 2022-05-20 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0011_remove_chargemixproduct_metal_recov_rate_lte_100_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargemix',
            old_name='fesimg_qty',
            new_name='fesimg_rec_rate',
        ),
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='product_curr_qty',
            new_name='curr_qty',
        ),
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='product_final_qty',
            new_name='final_qty',
        ),
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='product_max_qty',
            new_name='max_qty',
        ),
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='product_min_qty',
            new_name='min_qty',
        ),
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='product_qty_roundoff',
            new_name='qty_roundoff',
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='furnace_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='tapping_temp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chargemix',
            name='tapping_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='metal_recov_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
