# Generated by Django 4.0.4 on 2022-05-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0012_rename_fesimg_qty_chargemix_fesimg_rec_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargemixproduct',
            old_name='final_qty',
            new_name='optimized_qty',
        ),
    ]
