# Generated by Django 4.0.4 on 2022-05-21 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0013_rename_final_qty_chargemixproduct_optimized_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargemixproduct',
            name='metal_recov_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=4, validators=[django.core.validators.MaxValueValidator(100.01), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chargemixproduct',
            name='qty_roundoff',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
