# Generated by Django 4.0.4 on 2022-05-21 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newc', '0015_alter_chargemixproduct_metal_recov_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargemixproduct',
            name='metal_recov_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
